# When a merge to main is made
# Deploy main to Firebase
# And run tests

name: Deploy on Merge
'on':
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci && npm run build && npm test
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_ECM2434_GROUP_PROJECT }}'
          channelId: live
          projectId: ecm2434-group-project
